### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by JayJay1024** [helix-bridge/uniswap-interface#1]
### Branch

`jay/support-bitlayer-testnet`

### Node.js

> node v18, yarn v3

```bash
$ node -v
v18.20.3

$ yarn -v
3.2.3
```

### Install and Build

1. env

> For local, edit ~/.yarnrc.yml

```yml
npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
    npmAuthToken: "Your Github PCT"
```

> For GitHub Action

```yml
run: |
  yarn config set npmAuthToken ${{secrets.GITHUB_TOKEN}}
  yarn install --immutable
  yarn config unset npmAuthToken
```

2. cmd

```bash
$ yarn install --immutable
$ yarn web build
```

### Output

`apps/web/build`

### Refer

https://github.com/helix-bridge/uniswap-interface/pull/2/files#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3

### Home Page

https://helix-bridge.github.io/uniswap-interface/
